### ISSUE TITLE
500 error for CMAK (kafka manager)

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_docker#14]
cmak container is running, but web gui 500 Internal Privoxy Error
```
$ docker logs cmak

2021-02-24 15:29:14,644 - [WARN] o.a.z.ClientCnxn - Session 0x0 for server zoo:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address zoo:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:66)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:39)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1087)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1139)
2021-02-24 15:29:15,745 - [ERROR] o.a.z.c.StaticHostProvider - Unable to resolve address: zoo:2181
java.net.UnknownHostException: zoo
        at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:92)
        at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:147)
        at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:375)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1137)
2021-02-24 15:29:15,745 - [WARN] o.a.z.ClientCnxn - Session 0x0 for server zoo:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address zoo:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:66)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:39)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1087)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1139)

```

**Comment by zengxc-1996** [comment]
when I update hosts zoo to 172.17.0.1 in docker-compose
connection is ok !
![image](https://user-images.githubusercontent.com/63622990/109447665-1ebbee00-7a7f-11eb-8db4-1b696af23e0b.png)
docker-compose file:
```
      ZK_HOSTS: "172.17.0.1:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: username
      KAFKA_MANAGER_PASSWORD: password
```
it's can set a login auth;

when I connection: 
![image](https://user-images.githubusercontent.com/63622990/109447831-95f18200-7a7f-11eb-829d-0b05c2908795.png)
need add  the jmx on kafka:
```
/data/kafka/bin/kafka-run-class.sh: 
add  JMX_PORT=<jmx_port>

${JAVA_HOME}/jre/lib/management/jmxremote.access:
add jmx username password auth  
```

**Comment by qiaofeng1227** [comment]
wait for correct image, transfer to issue: https://github.com/Websoft9/ansible-kafka/issues/7
